run on examples in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,6 +74,19 @@ jobs:
       - name: Test
         shell: bash
         run: source ~/.profile && lake test
+      - name: Verify examples
+        shell: bash
+        run: |
+              DIR="Examples"
+              if [ ! -d "$DIR" ]; then
+              echo "Error: Directory '$DIR' does not exist"
+              exit 1
+              fi
+              find "$DIR" -maxdepth 1 -type f -name "*.st" | while IFS= read -r file; do
+                  filename=$(basename "$file")
+                  source ~/.profile && lake exe StrataVerify "$file"
+              done
+
 
   lint_checks:
     name: Run lint checks
